### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by DmitriiMelnikOnix** [Xitch89/ReactJS#41]
```javascript
className={theme === 'light' ? classes.ourServices_yellowTextLight : classes.ourServices_yellowTextDark}
```

Щоб не створювати однакові класи, можна скористатись css та зробити щось типу такого

```javascript
className={`${classes.ourServices_yellowText} ${theme === THEME_DARK && classes.dark}`}
```
Але якщо додати бібліотеку `classNames` або `clsx`
Можна зробити ще краще

```javascript
className={cn(classes.ourServices_yellowText, {[classes.dark]: theme === THEME_DARK})}
```

І в css щось таке

```css
.ourServices_yellowText {
   font: 400 24px/34px "Old+Standard+TT";
   padding: 20px 0 10px 61px;
   color: #000000;
}

.ourServices_yellowText.dark {
  color: #ffae2b;
}
```

Ще краще винести кольори css в змінні
